# Generated by Django 3.1.7 on 2021-04-10 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('credits', models.IntegerField(default=0)),
                ('contact_hours_Lecture', models.IntegerField(default=0)),
                ('contact_hours_Tutorial', models.IntegerField(default=0)),
                ('contact_hours_Lab', models.IntegerField(default=0)),
                ('contact_hours_Discussion', models.IntegerField(default=0)),
                ('contact_hours_Project', models.IntegerField(default=0)),
                ('syllabus', models.CharField(max_length=5000)),
                ('evaluation_schema_quiz1', models.IntegerField(default=0)),
                ('evaluation_schema_midsem', models.IntegerField(default=0)),
                ('evaluation_schema_quiz2', models.IntegerField(default=0)),
                ('evaluation_schema_lab', models.IntegerField(default=0)),
                ('evaluation_schema_endsem', models.IntegerField(default=0)),
                ('ref_books', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('batch_year', models.IntegerField(default=2021)),
                ('version', models.CharField(max_length=50)),
                ('present_curriculum', models.BooleanField(default=False)),
                ('no_of_semesters', models.IntegerField(default=8)),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_name', models.CharField(max_length=50)),
                ('department_head', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_no', models.IntegerField()),
                ('curriculum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program_and_curriculum_management.curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammeDiscipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program_and_curriculum_management.disciplinedepartment')),
                ('programme_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program_and_curriculum_management.programme')),
            ],
        ),
        migrations.AddField(
            model_name='curriculum',
            name='programme_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program_and_curriculum_management.programme'),
        ),
        migrations.CreateModel(
            name='CourseSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=1000, null=True)),
                ('course_type', models.CharField(choices=[('Professional Core', 'Professional Core'), ('Professional Elective', 'Professional Elective'), ('Professional Lab', 'Professional Lab'), ('Engineering Science', 'Engineering Science'), ('Natural Science', 'Natural Science'), ('Humanities', 'Humanities'), ('Design', 'Design'), ('Manufacturing', 'Manufacturing'), ('Management Science', 'Management Science')], default='', max_length=40, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program_and_curriculum_management.courses')),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program_and_curriculum_management.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=50)),
                ('curriculum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program_and_curriculum_management.curriculum')),
                ('discipline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program_and_curriculum_management.disciplinedepartment')),
            ],
        ),
    ]
