# Generated by Django 3.1.7 on 2021-03-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program_and_curriculum_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programme',
            old_name='name',
            new_name='title',
        ),
    ]
