# Generated by Django 3.1.7 on 2021-03-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_and_curriculum_management', '0003_auto_20210319_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='present_curriculum',
            field=models.BooleanField(default=True),
        ),
    ]
