# Generated by Django 3.1.7 on 2021-03-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_and_curriculum_management', '0004_curriculum_present_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='present_curriculum',
            field=models.BooleanField(default=False),
        ),
    ]
