# Generated by Django 3.1.7 on 2021-03-21 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program_and_curriculum_management', '0005_auto_20210319_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='semester_id',
        ),
    ]
