# Generated by Django 3.1.7 on 2021-03-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_and_curriculum_management', '0006_remove_courses_semester_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='evaluation_schema',
        ),
        migrations.AddField(
            model_name='courses',
            name='contact_hours_Discussion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courses',
            name='contact_hours_Project',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courses',
            name='evaluation_schema_endsem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courses',
            name='evaluation_schema_lab',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courses',
            name='evaluation_schema_midsem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courses',
            name='evaluation_schema_quiz1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courses',
            name='evaluation_schema_quiz2',
            field=models.IntegerField(default=0),
        ),
    ]
