# Generated by Django 3.1.7 on 2021-03-21 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program_and_curriculum_management', '0007_auto_20210321_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='course_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='program_and_curriculum_management.courses'),
        ),
    ]
