# Generated by Django 3.1.7 on 2021-03-24 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program_and_curriculum_management', '0009_auto_20210321_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='course_id',
        ),
        migrations.CreateModel(
            name='Semester_Course_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program_and_curriculum_management.courses')),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program_and_curriculum_management.semester')),
            ],
        ),
    ]
